In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
### Dropping unwanted features
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
# Encoding categorical columns
gender_encoder = LabelEncoder()
df['Gender'] = gender_encoder.fit_transform(df['Gender'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [6]:
# One hot encoding for Geography column
geo_encoder = OneHotEncoder(sparse_output=False)
geo_encoded = geo_encoder.fit_transform(df[['Geography']])
geo_encoded_df = pd.DataFrame(geo_encoded, columns=geo_encoder.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [7]:
# Combine all the columns with data
df = pd.concat([df.drop(['Geography'], axis=1), geo_encoded_df], axis=1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X = df.drop(['EstimatedSalary'], axis=1)
Y = df['EstimatedSalary']

In [9]:
# Split the data in train & test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### ANN Regression

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), # 1st Hidden Layer - Connected with Input
    Dense(32, activation='relu'), # 2nd Hidden Layer
    Dense(1) # Output Layer - Linear (By Default)
])

c:\ProgramData\miniconda3\envs\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.compile(
    optimizer='adam', loss='mean_absolute_error', metrics=['mae']
)

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [17]:
history = model.fit(
    X_train, Y_train, validation_data=(X_test, Y_test), epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100385.2891 - mae: 100385.2891 - val_loss: 98545.7031 - val_mae: 98545.7031
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99736.6094 - mae: 99736.6094 - val_loss: 97238.0234 - val_mae: 97238.0234
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 97450.2500 - mae: 97450.2500 - val_loss: 93880.7578 - val_mae: 93880.7578
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 92911.0469 - mae: 92911.0469 - val_loss: 88202.9297 - val_mae: 88202.9297
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 86135.6484 - mae: 86135.6484 - val_loss: 80637.5312 - val_mae: 80637.5312
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 77885.3281 - mae: 77885.3281 - val_loss: 72396.5078 - val_mae: 72396.5078
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 69418.7031 - mae: 69418.7031 - val_loss: 64679.8555 - val_mae: 64679.8555
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 62000.2695 - mae: 62000.2695 - val_loss: 58545.5703 - val_mae: 58545.5703
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56578.9453 - mae: 56578.9453 - val_loss: 54491.4297 - val_mae: 54491.4297
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53201.1172 - mae: 53201.1172 - val_loss: 52222.2695 - val_mae: 52222.2695
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51511.8555 - mae: 51511.8555 - val_loss: 51358.5273 - val_mae: 51358.5273
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50780.6133 - mae: 50780.6133 - val_loss: 51089.8828 - val_mae: 51089.8828
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50488.2930 - mae: 50488.2930 - val_loss: 50997.1523 - val_mae: 50997.1523
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50356.4766 - mae: 50356.4766 - val_loss: 50933.2305 - val_mae: 50933.2305
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50275.1445 - mae: 50275.1445 - val_loss: 50871.5938 - val_mae: 50871.5938
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50215.2305 - mae: 50215.2305 - val_loss: 50822.3672 - val_mae: 50822.3672
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50163.8008 - mae: 50163.8008 - val_loss: 50763.0742 - val_mae: 50763.0742
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50120.5898 - mae: 50120.5898 - val_loss: 50717.0508 - val_mae: 50717.0508
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50079.2930 - mae: 50079.2930 - val_loss: 50672.6328 - val_mae: 50672.6328
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50041.3008 - mae: 50041.3008 - val_loss: 50634.0898 - val_mae: 50634.0898
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50006.9492 - mae: 50006.9492 - val_loss: 50595.0195 - val_mae: 50595.0195
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49976.7461 - mae: 49976.7461 - val_loss: 50571.6602 - val_mae: 50571.6602
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49946.3672 - mae: 49946.3672 - val_loss: 50542.6641 - val_mae: 50542.6641
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49919.6836 - mae: 49919.6836 - val_loss: 50518.9688 - val_mae: 50518.9688
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49898.0430 - mae: 49898.0430 - val_loss: 50488.5273 - val_mae: 50488.5273
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49867.5508 - mae: 49867.5508 - val_loss: 50478.3320 - val_mae: 50478.3320
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49849.5117 - mae: 49849.5117 - val_loss: 50463.5234 - val_mae: 50463.5234
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49824.9766 - mae: 49824.9766 - val_loss: 50443.4922 - val_mae: 50443.4922
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49804.1758 - mae: 49804.1758 - val_loss: 50428.8555 - val_mae: 50428.8555
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49788.0781 - mae: 49788.0781 - val_loss: 50415.1523 - val_mae: 50415.1523
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49769.4375 - mae: 49769.4375 - val_loss: 50414.3789 - val_mae: 50414.3789
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49754.8125 - mae: 49754.8125 - val_loss: 50401.8594 - val_mae: 50401.8594
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 49735.5508 - mae: 49735.5508 - val_loss: 50382.6250 - val_mae: 50382.6250
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49721.7734 - mae: 49721.7734 - val_loss: 50377.4570 - val_mae: 50377.4570
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49706.9297 - mae: 49706.9297 - val_loss: 50368.8242 - val_mae: 50368.8242
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49692.6016 - mae: 49692.6016 - val_loss: 50355.0078 - val_mae: 50355.0078
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49677.6172 - mae: 49677.6172 - val_loss: 50352.8555 - val_mae: 50352.8555
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49662.3477 - mae: 49662.3477 - val_loss: 50352.0938 - val_mae: 50352.0938
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49651.7539 - mae: 49651.7539 - val_loss: 50345.1562 - val_mae: 50345.1562
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49640.6406 - mae: 49640.6406 - val_loss: 50338.9570 - val_mae: 50338.9570
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49631.0781 - mae: 49631.0781 - val_loss: 50328.6758 - val_mae: 50328.6758
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49617.5352 - mae: 49617.5352 - val_loss: 50329.7617 - val_mae: 50329.7617
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49610.2188 - mae: 49610.2188 - val_loss: 50324.2148 - val_mae: 50324.2148
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49597.2344 - mae: 49597.2344 - val_loss: 50320.1289 - val_mae: 50320.1289
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49586.2188 - mae: 49586.2188 - val_loss: 50324.2422 - val_mae: 50324.2422
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49581.1875 - mae: 49581.1875 - val_loss: 50315.1914 - val_mae: 50315.1914
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49569.7109 - mae: 49569.7109 - val_loss: 50307.4336 - val_mae: 50307.4336
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49562.8516 - mae: 49562.8516 - val_loss: 50307.8906 - val_mae: 50307.8906
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49553.6914 - mae: 49553.6914 - val_loss: 50312.5430 - val_mae: 50312.5430
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49547.7695 - mae: 49547.7695 - val_loss: 50319.5781 - val_mae: 50319.5781
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49537.1797 - mae: 49537.1797 - val_loss: 50315.9492 - val_mae: 50315.9492
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49529.9375 - mae: 49529.9375 - val_loss: 50317.5234 - val_mae: 50317.5234
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49523.3125 - mae: 49523.3125 - val_loss: 50318.3828 - val_mae: 50318.3828
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49515.3594 - mae: 49515.3594 - val_loss: 50316.0586 - val_mae: 50316.0586
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49509.9961 - mae: 49509.9961 - val_loss: 50310.5391 - val_mae: 50310.5391
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49500.6680 - mae: 49500.6680 - val_loss: 50296.8555 - val_mae: 50296.8555
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49497.0391 - mae: 49497.0391 - val_loss: 50312.7344 - val_mae: 50312.7344
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49487.2383 - mae: 49487.2383 - val_loss: 50297.4570 - val_mae: 50297.4570
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49480.6250 - mae: 49480.6250 - val_loss: 50295.0039 - val_mae: 50295.0039
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49475.6914 - mae: 49475.6914 - val_loss: 50306.0938 - val_mae: 50306.0938
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49467.9336 - mae: 49467.9336 - val_loss: 50297.0273 - val_mae: 50297.0273
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49465.9727 - mae: 49465.9727 - val_loss: 50293.4961 - val_mae: 50293.4961
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49458.5391 - mae: 49458.5391 - val_loss: 50291.4844 - val_mae: 50291.4844
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49451.3672 - mae: 49451.3672 - val_loss: 50292.4570 - val_mae: 50292.4570
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49446.8789 - mae: 49446.8789 - val_loss: 50299.1719 - val_mae: 50299.1719
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49443.3672 - mae: 49443.3672 - val_loss: 50303.2891 - val_mae: 50303.2891
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49437.8398 - mae: 49437.8398 - val_loss: 50300.6367 - val_mae: 50300.6367
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49431.2969 - mae: 49431.2969 - val_loss: 50297.8594 - val_mae: 50297.8594
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49427.4336 - mae: 49427.4336 - val_loss: 50297.3047 - val_mae: 50297.3047
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49423.5391 - mae: 49423.5391 - val_loss: 50302.1875 - val_mae: 50302.1875
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49420.7031 - mae: 49420.7031 - val_loss: 50300.5547 - val_mae: 50300.5547
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49419.6445 - mae: 49419.6445 - val_loss: 50298.4648 - val_mae: 50298.4648
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49410.5703 - mae: 49410.5703 - val_loss: 50301.8047 - val_mae: 50301.8047

In [18]:
## Load Tensorboard
%reload_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit --port 6007

In [20]:
# Model Evaluation
test_loss, test_mae =  model.evaluate(X_test, Y_test)
print(f"Test MAE : {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - loss: 50291.4844 - mae: 50291.4844
Test MAE : 50291.484375

In [21]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.